### PR TITLE
Added promises section

### PR DESCRIPTION
**Pull request by charly22**
This is just a proposal, in case you don't agree we can discuss it over here.

### CODE REVIEW

**Comment by maxigimenez** [comment]
:shipit: :+1:

**Comment by dottavio** [comment]
:ship: yep, ya mismo lo cambio en zoolander :+1:

**Comment by homer0** [comment]
:anchor: !

**Comment by loverajoel** [comment]
I like it :rocket:

**Comment by charly22** [comment]
@iuga please take a look at this whenever you have the change. Thanks

**Pull request merged**
